# Generated by Django 2.2 on 2021-01-28 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RetailerDB',
            fields=[
                ('retailerID', models.AutoField(primary_key=True, serialize=False)),
                ('retailerName', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=128)),
            ],
        ),
    ]
