# Generated by Django 2.2 on 2021-02-12 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shopper', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderDB',
            fields=[
                ('orderID', models.AutoField(primary_key=True, serialize=False)),
                ('productsOrdered', models.TextField()),
                ('totalPrice', models.FloatField()),
                ('status', models.CharField(max_length=50)),
                ('orderedBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderedByWhom', to='shopper.ShopperDB')),
            ],
        ),
    ]
