# Generated by Django 2.2 on 2021-02-07 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdb',
            name='orderedBy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderedByWhom', to='shopper.ShopperDB', to_field='shopperID'),
        ),
    ]
