# Generated by Django 2.2 on 2021-02-07 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopper', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shopperdb',
            old_name='shopperID',
            new_name='shopperId',
        ),
    ]
