NEXTGENSHOP_BACKEND_IMAGE?=nextgenshop/backend
NEXTGENSHOP_BACKEND_PORT?=80

build:
	docker build --tag=${NEXTGENSHOP_BACKEND_IMAGE} .

run: build
	docker run --rm \
		-p ${NEXTGENSHOP_BACKEND_PORT}:8000 \
		${NEXTGENSHOP_BACKEND_IMAGE}
