# Generated by Django 2.2 on 2021-01-28 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('retailer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductDB',
            fields=[
                ('productID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('image', models.TextField()),
                ('price', models.FloatField()),
                ('stock', models.FloatField()),
                ('soldBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soldByWhom', to='retailer.RetailerDB')),
            ],
        ),
    ]
