# Generated by Django 2.2 on 2021-02-12 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductDB',
            fields=[
                ('productId', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('image', models.TextField(null=True)),
                ('price', models.FloatField()),
                ('stock', models.PositiveIntegerField(default=1)),
                ('retailer', models.CharField(max_length=100)),
            ],
        ),
    ]
