# Generated by Django 2.2 on 2021-01-29 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdb',
            name='image',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='productdb',
            name='soldBy',
            field=models.CharField(max_length=100),
        ),
    ]
