# Generated by Django 2.2 on 2021-03-04 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdb',
            name='views',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
