# Generated by Django 2.2 on 2021-02-07 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20210129_0005'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productdb',
            old_name='productID',
            new_name='productId',
        ),
    ]
