# Generated by Django 2.2 on 2021-03-10 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BasketDB',
            fields=[
                ('basketId', models.AutoField(primary_key=True, serialize=False)),
                ('shopperId', models.IntegerField(unique=True)),
                ('totalPrice', models.FloatField(default=0, null=True)),
                ('isEmpty', models.BooleanField(default=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BasketItem',
            fields=[
                ('basketItemId', models.AutoField(primary_key=True, serialize=False)),
                ('basketId', models.IntegerField()),
                ('productId', models.IntegerField()),
                ('quantity', models.IntegerField()),
            ],
        ),
    ]
