# Generated by Django 2.2 on 2021-02-11 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BasketDB',
            fields=[
                ('shopperId', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('items', models.CharField(max_length=100, null=True)),
                ('totalPrice', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='BasketItem',
            fields=[
                ('basketItemId', models.AutoField(primary_key=True, serialize=False)),
                ('shopperId', models.IntegerField()),
                ('productId', models.IntegerField()),
                ('quantity', models.FloatField()),
            ],
        ),
    ]
