# Generated by Django 2.2 on 2021-02-01 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_basket', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BasketItem',
            fields=[
                ('basketItemID', models.AutoField(primary_key=True, serialize=False)),
                ('basketID', models.IntegerField()),
                ('productID', models.IntegerField()),
                ('quantity', models.FloatField()),
            ],
        ),
        migrations.RenameField(
            model_name='basketdb',
            old_name='quantity',
            new_name='totalPrice',
        ),
        migrations.AddField(
            model_name='basketdb',
            name='shopper',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
