# Generated by Django 2.2 on 2021-02-03 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_basket', '0003_auto_20210203_0031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basketdb',
            name='basketID',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='basketitem',
            name='basketItemID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
