# Generated by Django 2.2 on 2021-02-07 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_basket', '0006_auto_20210207_1536'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basketdb',
            name='basketID',
        ),
        migrations.AlterField(
            model_name='basketdb',
            name='shopperID',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
