# Generated by Django 2.2 on 2021-02-07 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_basket', '0007_auto_20210207_1552'),
    ]

    operations = [
        migrations.RenameField(
            model_name='basketdb',
            old_name='shopperID',
            new_name='shopperId',
        ),
        migrations.RenameField(
            model_name='basketitem',
            old_name='basketItemID',
            new_name='basketItemId',
        ),
        migrations.RenameField(
            model_name='basketitem',
            old_name='productID',
            new_name='productId',
        ),
        migrations.RenameField(
            model_name='basketitem',
            old_name='shopperID',
            new_name='shopperId',
        ),
    ]
