# Generated by Django 2.2 on 2021-02-07 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_basket', '0008_auto_20210207_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basketdb',
            name='items',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
